# This configuration uses Cloud Build with Buildpacks for a Python application

steps:
  - name: 'gcr.io/buildpacks/pack'  # Build using Buildpacks
    args:
      - 'build'
      - 'advance-stratum-409704/ai-assistant'  # Replace with your desired image name
      - '--builder=gcr.io/buildpacks/builder'
      - '--env=GOOGLE_RUNTIME=python'  # Set runtime environment
      - '.'  # Current directory (source code)
  - name: 'gcr.io/cloud-builders/gcloud'  # Deploy to Cloud Run
    args:
      - 'run'
      - 'deploy'
      - 'ai-assistant'  # Service name
      - '--image'
      - 'advance-stratum-409704/ai-assistant'
      - '--region'
      - 'asia-south2'  # Replace with your desired region
      - '--allow-unauthenticated'  # Remove for production!

secrets:  # Define secrets here
  secretEnv:
    HANDWRITTEN_RECOGNITION_API_KEY: handwritten_recognition
    OPENAI_API_KEY: OPENAI_API_KEY
    SPEECH_TO_TEXT_API_KEY: speech_to_text
    TEXT_TO_SPEECH_API_KEY: text_to_speech
    TRANSLATION_API_KEY: translation
