stages:
- build
  - name: 'cloudbuild.googleapis.com/builders/python:latest'  # Replace with your project ID and desired image name
    substitutions:
      _PROJECT_ID: advance-stratum-409704
    steps:
      - name: 'gcloud run deploy'
        args: ['build', '-t', 'advance-stratum-409704/ai-assistant:latest', '.']
  - name: 'gcloud run deploy'
    args: ['ai-assistant', '--image', 'advance-stratum-409704/ai-assistant:latest', 
           '--region', 'asia-south2', 
           --set-env-vars: 'HANDWRITTEN_RECOGNITION_API_KEY=handwritten_recognition', 
               'OPENAI_API_KEY=OPENAI_API_KEY', 
               'SPEECH_TO_TEXT_API_KEY=speech_to_text', 
               'TEXT_TO_SPEECH_API_KEY=text_to_speech', 
               'TRANSLATION_API_KEY=translation', '--pack', 'true']  
    secretEnvVars:
      HANDWRITTEN_RECOGNITION_API_KEY: handwritten_recognition
      OPENAI_API_KEY: OPENAI_API_KEY  
      SPEECH_TO_TEXT_API_KEY: speech_to_text
      TEXT_TO_SPEECH_API_KEY: text_to_speech
      TRANSLATION_API_KEY: translation

